# Generated by Django 4.2.7 on 2023-12-05 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('idInscricao', models.AutoField(primary_key=True, serialize=False)),
                ('nicknamejogo', models.CharField(max_length=60)),
                ('rankJogo', models.CharField(max_length=60)),
                ('personagemJogo', models.CharField(blank=True, max_length=60, null=True)),
                ('experiencia', models.TextField()),
                ('disponibilidade', models.CharField(max_length=60)),
                ('raMaua', models.CharField(max_length=60)),
                ('datapreenchimento', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'inscricao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('idJogo', models.IntegerField(primary_key=True, serialize=False)),
                ('nomeJogo', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'jogo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
